@startuml storepulse-iam-web-component

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_LEFT_RIGHT()
HIDE_STEREOTYPE()
skinparam shadowing false
skinparam defaultFontName Arial

title StorePulse - Identity and Access Management - Web Components

Container_Boundary(webApp, "Web Application - Angular") {

    Component(iamWebUI, "Identity & Access UI", "Angular", "Provides sign-up, sign-in and password recovery screens for the Gallery Administrator.")

    Component(iamWebService, "Identity & Access Service", "Angular Service", "Consumes authentication and password recovery REST endpoints, and stores the access token.")
}

Container(restApi, "REST API", "ASP.NET Core, .NET", "Monolithic backend that centralizes StorePulse business logic.")

Rel(iamWebUI, iamWebService, "Uses")

Rel(iamWebService, restApi, "Consumes authentication services", "HTTPS/JSON")

@enduml
