@startuml storepulse-service-monitoring-mobile-component

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_LEFT_RIGHT()
HIDE_STEREOTYPE()
skinparam shadowing false
skinparam defaultFontName Arial

title StorePulse - Service Execution and Monitoring - Mobile Components

Container_Boundary(mobileApp, "Mobile Application - Flutter") {

    Component(monitoringUI, "Monitoring UI", "Flutter, Dart", "Provides monitoring views for measurements, consumption and alerts.")

    Component(monitoringService, "Monitoring Service", "Dart", "Consumes REST services for telemetry, measurements and alerts.")
}

Container(restApi, "REST API", "ASP.NET Core, .NET", "Monolithic backend that centralizes StorePulse business logic.")

Rel(monitoringUI, monitoringService, "Uses")

Rel(monitoringService, restApi, "Consumes monitoring services", "HTTPS/JSON")

@enduml