@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_LEFT_RIGHT()
HIDE_STEREOTYPE()

skinparam shadowing false
skinparam defaultFontName Arial

title Management-Tenant Communication - Mobile Application Component View

Person(tenant, "Tenant", "Tenant of a commercial gallery.")

Container_Boundary(mobileApplication, "Mobile Application") {

    Component(mobileComponents, "Mobile Components", "Mobile Component", "Mobile interface for consulting conversations, notifications and assignments.")

    Component(conversationsController, "Conversations Controller", "Controller", "Manages conversations.")

    Component(conversationMessagesController, "Conversation Messages Controller", "Controller", "Manages conversation messages.")

    Component(tenantNotificationsController, "Tenant Notifications Controller", "Controller", "Manages tenant notifications.")
}

Rel(tenant, mobileComponents, "Queries conversations, notifications and assignments")

Rel(mobileComponents, conversationsController, "Queries conversations", "HTTPS/JSON")

Rel(mobileComponents, conversationMessagesController, "Sends and queries messages", "HTTPS/JSON")

Rel(mobileComponents, tenantNotificationsController, "Queries notifications", "HTTPS/JSON")

@enduml