@startuml storepulse-analytics-mobile-component

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_LEFT_RIGHT()
HIDE_STEREOTYPE()
skinparam shadowing false
skinparam defaultFontName Arial

title StorePulse - Analytics - Mobile Components

Container_Boundary(mobileApp, "Mobile Application - Flutter") {

    Component(analyticsMobileUI, "Analytics UI", "Flutter, Dart", "Displays the Local Dashboard and the Notification Center for the Tenant.")

    Component(analyticsMobileService, "Analytics Service", "Dart", "Consumes the dashboard and notification REST endpoints.")
}

Container(restApi, "REST API", "ASP.NET Core, .NET", "Monolithic backend that centralizes StorePulse business logic.")

Rel(analyticsMobileUI, analyticsMobileService, "Uses")

Rel(analyticsMobileService, restApi, "Consumes notification and dashboard services", "HTTPS/JSON")

@enduml
